# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: networking/v1alpha3/pluginmanager.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='networking/v1alpha3/pluginmanager.proto',
  package='istio.networking.v1alpha3',
  syntax='proto3',
  serialized_options=_b('Z istio.io/api/networking/v1alpha3'),
  serialized_pb=_b('\n\'networking/v1alpha3/pluginmanager.proto\x12\x19istio.networking.v1alpha3\x1a\x1cgoogle/protobuf/struct.proto\"\xe2\x01\n\rPluginManager\x12U\n\x0fworkload_labels\x18\x01 \x03(\x0b\x32<.istio.networking.v1alpha3.PluginManager.WorkloadLabelsEntry\x12\x31\n\x06plugin\x18\x02 \x03(\x0b\x32!.istio.networking.v1alpha3.Plugin\x12\x10\n\x08gateways\x18\x03 \x03(\t\x1a\x35\n\x13WorkloadLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"Q\n\x06Plugin\x12\x0e\n\x06\x65nable\x18\x01 \x01(\x08\x12\x0c\n\x04name\x18\x02 \x01(\t\x12)\n\x08settings\x18\x03 \x01(\x0b\x32\x17.google.protobuf.StructB\"Z istio.io/api/networking/v1alpha3b\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_PLUGINMANAGER_WORKLOADLABELSENTRY = _descriptor.Descriptor(
  name='WorkloadLabelsEntry',
  full_name='istio.networking.v1alpha3.PluginManager.WorkloadLabelsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='istio.networking.v1alpha3.PluginManager.WorkloadLabelsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='istio.networking.v1alpha3.PluginManager.WorkloadLabelsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=327,
)

_PLUGINMANAGER = _descriptor.Descriptor(
  name='PluginManager',
  full_name='istio.networking.v1alpha3.PluginManager',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workload_labels', full_name='istio.networking.v1alpha3.PluginManager.workload_labels', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='plugin', full_name='istio.networking.v1alpha3.PluginManager.plugin', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gateways', full_name='istio.networking.v1alpha3.PluginManager.gateways', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PLUGINMANAGER_WORKLOADLABELSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=327,
)


_PLUGIN = _descriptor.Descriptor(
  name='Plugin',
  full_name='istio.networking.v1alpha3.Plugin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enable', full_name='istio.networking.v1alpha3.Plugin.enable', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='istio.networking.v1alpha3.Plugin.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='settings', full_name='istio.networking.v1alpha3.Plugin.settings', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=410,
)

_PLUGINMANAGER_WORKLOADLABELSENTRY.containing_type = _PLUGINMANAGER
_PLUGINMANAGER.fields_by_name['workload_labels'].message_type = _PLUGINMANAGER_WORKLOADLABELSENTRY
_PLUGINMANAGER.fields_by_name['plugin'].message_type = _PLUGIN
_PLUGIN.fields_by_name['settings'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['PluginManager'] = _PLUGINMANAGER
DESCRIPTOR.message_types_by_name['Plugin'] = _PLUGIN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PluginManager = _reflection.GeneratedProtocolMessageType('PluginManager', (_message.Message,), dict(

  WorkloadLabelsEntry = _reflection.GeneratedProtocolMessageType('WorkloadLabelsEntry', (_message.Message,), dict(
    DESCRIPTOR = _PLUGINMANAGER_WORKLOADLABELSENTRY,
    __module__ = 'networking.v1alpha3.pluginmanager_pb2'
    # @@protoc_insertion_point(class_scope:istio.networking.v1alpha3.PluginManager.WorkloadLabelsEntry)
    ))
  ,
  DESCRIPTOR = _PLUGINMANAGER,
  __module__ = 'networking.v1alpha3.pluginmanager_pb2'
  # @@protoc_insertion_point(class_scope:istio.networking.v1alpha3.PluginManager)
  ))
_sym_db.RegisterMessage(PluginManager)
_sym_db.RegisterMessage(PluginManager.WorkloadLabelsEntry)

Plugin = _reflection.GeneratedProtocolMessageType('Plugin', (_message.Message,), dict(
  DESCRIPTOR = _PLUGIN,
  __module__ = 'networking.v1alpha3.pluginmanager_pb2'
  # @@protoc_insertion_point(class_scope:istio.networking.v1alpha3.Plugin)
  ))
_sym_db.RegisterMessage(Plugin)


DESCRIPTOR._options = None
_PLUGINMANAGER_WORKLOADLABELSENTRY._options = None
# @@protoc_insertion_point(module_scope)
