// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: networking/v1alpha3/gateway_plugin.proto

package v1alpha3

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type GatewayPlugin struct {
	// route level plugin
	Route []string `protobuf:"bytes,1,rep,name=route,proto3" json:"route,omitempty"`
	// host level plugin
	Host []string `protobuf:"bytes,2,rep,name=host,proto3" json:"host,omitempty"`
	// service level plugin
	Service []string `protobuf:"bytes,3,rep,name=service,proto3" json:"service,omitempty"`
	// plugin settings
	Settings *types.Struct `protobuf:"bytes,4,opt,name=settings,proto3" json:"settings,omitempty"`
	// which gateway should use this plugin setting
	Gateway []string `protobuf:"bytes,5,rep,name=gateway,proto3" json:"gateway,omitempty"`
	// which user should use this plugin setting
	User []string `protobuf:"bytes,6,rep,name=user,proto3" json:"user,omitempty"`
	// plugin name is the name of plugin, such as envoy.util, com.netease.transformation
	PluginName           string   `protobuf:"bytes,7,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GatewayPlugin) Reset()         { *m = GatewayPlugin{} }
func (m *GatewayPlugin) String() string { return proto.CompactTextString(m) }
func (*GatewayPlugin) ProtoMessage()    {}
func (*GatewayPlugin) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde08958efb731f8, []int{0}
}
func (m *GatewayPlugin) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GatewayPlugin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GatewayPlugin.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GatewayPlugin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatewayPlugin.Merge(m, src)
}
func (m *GatewayPlugin) XXX_Size() int {
	return m.Size()
}
func (m *GatewayPlugin) XXX_DiscardUnknown() {
	xxx_messageInfo_GatewayPlugin.DiscardUnknown(m)
}

var xxx_messageInfo_GatewayPlugin proto.InternalMessageInfo

func (m *GatewayPlugin) GetRoute() []string {
	if m != nil {
		return m.Route
	}
	return nil
}

func (m *GatewayPlugin) GetHost() []string {
	if m != nil {
		return m.Host
	}
	return nil
}

func (m *GatewayPlugin) GetService() []string {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *GatewayPlugin) GetSettings() *types.Struct {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *GatewayPlugin) GetGateway() []string {
	if m != nil {
		return m.Gateway
	}
	return nil
}

func (m *GatewayPlugin) GetUser() []string {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *GatewayPlugin) GetPluginName() string {
	if m != nil {
		return m.PluginName
	}
	return ""
}

func init() {
	proto.RegisterType((*GatewayPlugin)(nil), "istio.networking.v1alpha3.GatewayPlugin")
}

func init() {
	proto.RegisterFile("networking/v1alpha3/gateway_plugin.proto", fileDescriptor_fde08958efb731f8)
}

var fileDescriptor_fde08958efb731f8 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0xbd, 0x4e, 0xc3, 0x30,
	0x18, 0x94, 0xe9, 0x1f, 0x75, 0xc5, 0x62, 0x21, 0x61, 0x10, 0x0a, 0x11, 0x53, 0x26, 0x5b, 0x90,
	0x37, 0x60, 0x61, 0x43, 0x28, 0x6c, 0x2c, 0x95, 0x5b, 0x7d, 0xb8, 0x16, 0x69, 0x1c, 0xd9, 0x9f,
	0x5b, 0xf1, 0x86, 0x8c, 0x6c, 0xac, 0x28, 0x4f, 0x82, 0x62, 0x37, 0xb0, 0x74, 0xfb, 0xee, 0x74,
	0xbe, 0x3b, 0x1f, 0x2d, 0x1a, 0xc0, 0xbd, 0x75, 0xef, 0xa6, 0xd1, 0x72, 0x77, 0xa7, 0xea, 0x76,
	0xa3, 0x4a, 0xa9, 0x15, 0xc2, 0x5e, 0x7d, 0x2c, 0xdb, 0x3a, 0x68, 0xd3, 0x88, 0xd6, 0x59, 0xb4,
	0xec, 0xd2, 0x78, 0x34, 0x56, 0xfc, 0xeb, 0xc5, 0xa0, 0xbf, 0xba, 0xd6, 0xd6, 0xea, 0x1a, 0x64,
	0x14, 0xae, 0xc2, 0x9b, 0xf4, 0xe8, 0xc2, 0x1a, 0xd3, 0xc3, 0xdb, 0x6f, 0x42, 0xcf, 0x1e, 0x93,
	0xe3, 0x73, 0x34, 0x64, 0xe7, 0x74, 0xe2, 0x6c, 0x40, 0xe0, 0x24, 0x1f, 0x15, 0xf3, 0x2a, 0x01,
	0xc6, 0xe8, 0x78, 0x63, 0x3d, 0xf2, 0x93, 0x48, 0xc6, 0x9b, 0x71, 0x3a, 0xf3, 0xe0, 0x76, 0x66,
	0x0d, 0x7c, 0x14, 0xe9, 0x01, 0xb2, 0x92, 0x9e, 0x7a, 0x40, 0x34, 0x8d, 0xf6, 0x7c, 0x9c, 0x93,
	0x62, 0x71, 0x7f, 0x21, 0x52, 0x0d, 0x31, 0xd4, 0x10, 0x2f, 0xb1, 0x46, 0xf5, 0x27, 0xec, 0xed,
	0x0e, 0x7f, 0xe3, 0x93, 0x64, 0x77, 0x80, 0x7d, 0x78, 0xf0, 0xe0, 0xf8, 0x34, 0x85, 0xf7, 0x37,
	0xbb, 0xa1, 0x8b, 0xb4, 0xc0, 0xb2, 0x51, 0x5b, 0xe0, 0xb3, 0x9c, 0x14, 0xf3, 0x8a, 0x26, 0xea,
	0x49, 0x6d, 0xe1, 0x41, 0x7c, 0x76, 0x19, 0xf9, 0xea, 0x32, 0xf2, 0xd3, 0x65, 0xe4, 0x35, 0x4f,
	0x03, 0x19, 0x2b, 0x55, 0x6b, 0xe4, 0x91, 0x5d, 0x57, 0xd3, 0xd8, 0xac, 0xfc, 0x0d, 0x00, 0x00,
	0xff, 0xff, 0x1b, 0x6b, 0xe4, 0x75, 0x75, 0x01, 0x00, 0x00,
}

func (m *GatewayPlugin) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GatewayPlugin) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GatewayPlugin) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.PluginName) > 0 {
		i -= len(m.PluginName)
		copy(dAtA[i:], m.PluginName)
		i = encodeVarintGatewayPlugin(dAtA, i, uint64(len(m.PluginName)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.User) > 0 {
		for iNdEx := len(m.User) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.User[iNdEx])
			copy(dAtA[i:], m.User[iNdEx])
			i = encodeVarintGatewayPlugin(dAtA, i, uint64(len(m.User[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Gateway) > 0 {
		for iNdEx := len(m.Gateway) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Gateway[iNdEx])
			copy(dAtA[i:], m.Gateway[iNdEx])
			i = encodeVarintGatewayPlugin(dAtA, i, uint64(len(m.Gateway[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.Settings != nil {
		{
			size, err := m.Settings.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGatewayPlugin(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.Service) > 0 {
		for iNdEx := len(m.Service) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Service[iNdEx])
			copy(dAtA[i:], m.Service[iNdEx])
			i = encodeVarintGatewayPlugin(dAtA, i, uint64(len(m.Service[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Host) > 0 {
		for iNdEx := len(m.Host) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Host[iNdEx])
			copy(dAtA[i:], m.Host[iNdEx])
			i = encodeVarintGatewayPlugin(dAtA, i, uint64(len(m.Host[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Route) > 0 {
		for iNdEx := len(m.Route) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Route[iNdEx])
			copy(dAtA[i:], m.Route[iNdEx])
			i = encodeVarintGatewayPlugin(dAtA, i, uint64(len(m.Route[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintGatewayPlugin(dAtA []byte, offset int, v uint64) int {
	offset -= sovGatewayPlugin(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GatewayPlugin) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Route) > 0 {
		for _, s := range m.Route {
			l = len(s)
			n += 1 + l + sovGatewayPlugin(uint64(l))
		}
	}
	if len(m.Host) > 0 {
		for _, s := range m.Host {
			l = len(s)
			n += 1 + l + sovGatewayPlugin(uint64(l))
		}
	}
	if len(m.Service) > 0 {
		for _, s := range m.Service {
			l = len(s)
			n += 1 + l + sovGatewayPlugin(uint64(l))
		}
	}
	if m.Settings != nil {
		l = m.Settings.Size()
		n += 1 + l + sovGatewayPlugin(uint64(l))
	}
	if len(m.Gateway) > 0 {
		for _, s := range m.Gateway {
			l = len(s)
			n += 1 + l + sovGatewayPlugin(uint64(l))
		}
	}
	if len(m.User) > 0 {
		for _, s := range m.User {
			l = len(s)
			n += 1 + l + sovGatewayPlugin(uint64(l))
		}
	}
	l = len(m.PluginName)
	if l > 0 {
		n += 1 + l + sovGatewayPlugin(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovGatewayPlugin(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGatewayPlugin(x uint64) (n int) {
	return sovGatewayPlugin(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GatewayPlugin) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGatewayPlugin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GatewayPlugin: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GatewayPlugin: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Route", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayPlugin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Route = append(m.Route, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Host", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayPlugin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Host = append(m.Host, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Service", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayPlugin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Service = append(m.Service, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Settings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayPlugin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Settings == nil {
				m.Settings = &types.Struct{}
			}
			if err := m.Settings.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Gateway", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayPlugin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Gateway = append(m.Gateway, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayPlugin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.User = append(m.User, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PluginName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayPlugin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PluginName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGatewayPlugin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGatewayPlugin(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGatewayPlugin
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGatewayPlugin
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGatewayPlugin
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGatewayPlugin
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthGatewayPlugin
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowGatewayPlugin
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipGatewayPlugin(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthGatewayPlugin
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthGatewayPlugin = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGatewayPlugin   = fmt.Errorf("proto: integer overflow")
)
