// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: networking/v1alpha3/version_manager.proto

package v1alpha3

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type VersionManager struct {
	//If no version is specified, the default version is injected
	DefaultVersion string `protobuf:"bytes,1,opt,name=default_version,json=defaultVersion,proto3" json:"default_version,omitempty"`
	//Upgrade failed retry policy
	RetryPolicy *RetryPolicy `protobuf:"bytes,4,opt,name=retry_policy,json=retryPolicy,proto3" json:"retry_policy,omitempty"`
	//Specify upgrade pod range
	SidecarVersionSpec []*SidecarVersionSpec `protobuf:"bytes,2,rep,name=sidecar_version_spec,json=sidecarVersionSpec,proto3" json:"sidecar_version_spec,omitempty"`
	//Upgrade state under namespace
	Status               *Status  `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionManager) Reset()         { *m = VersionManager{} }
func (m *VersionManager) String() string { return proto.CompactTextString(m) }
func (*VersionManager) ProtoMessage()    {}
func (*VersionManager) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec525f68b6c4927b, []int{0}
}
func (m *VersionManager) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VersionManager) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VersionManager.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VersionManager) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionManager.Merge(m, src)
}
func (m *VersionManager) XXX_Size() int {
	return m.Size()
}
func (m *VersionManager) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionManager.DiscardUnknown(m)
}

var xxx_messageInfo_VersionManager proto.InternalMessageInfo

func (m *VersionManager) GetDefaultVersion() string {
	if m != nil {
		return m.DefaultVersion
	}
	return ""
}

func (m *VersionManager) GetRetryPolicy() *RetryPolicy {
	if m != nil {
		return m.RetryPolicy
	}
	return nil
}

func (m *VersionManager) GetSidecarVersionSpec() []*SidecarVersionSpec {
	if m != nil {
		return m.SidecarVersionSpec
	}
	return nil
}

func (m *VersionManager) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type SidecarVersionSpec struct {
	// Types that are valid to be assigned to Selector:
	//	*SidecarVersionSpec_ViaDeployment
	//	*SidecarVersionSpec_ViaService
	//	*SidecarVersionSpec_ViaStatefulSet
	//	*SidecarVersionSpec_ViaLabelSelector
	Selector        isSidecarVersionSpec_Selector `protobuf_oneof:"selector"`
	ExpectedVersion string                        `protobuf:"bytes,5,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	// calculate hashcode of pods update status , to confirm if an update is needed
	PodsHash             string   `protobuf:"bytes,6,opt,name=pods_hash,json=podsHash,proto3" json:"pods_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SidecarVersionSpec) Reset()         { *m = SidecarVersionSpec{} }
func (m *SidecarVersionSpec) String() string { return proto.CompactTextString(m) }
func (*SidecarVersionSpec) ProtoMessage()    {}
func (*SidecarVersionSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec525f68b6c4927b, []int{1}
}
func (m *SidecarVersionSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SidecarVersionSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SidecarVersionSpec.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SidecarVersionSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SidecarVersionSpec.Merge(m, src)
}
func (m *SidecarVersionSpec) XXX_Size() int {
	return m.Size()
}
func (m *SidecarVersionSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_SidecarVersionSpec.DiscardUnknown(m)
}

var xxx_messageInfo_SidecarVersionSpec proto.InternalMessageInfo

type isSidecarVersionSpec_Selector interface {
	isSidecarVersionSpec_Selector()
	MarshalTo([]byte) (int, error)
	Size() int
}

type SidecarVersionSpec_ViaDeployment struct {
	ViaDeployment *ViaDeployment `protobuf:"bytes,1,opt,name=via_deployment,json=viaDeployment,proto3,oneof"`
}
type SidecarVersionSpec_ViaService struct {
	ViaService *ViaService `protobuf:"bytes,2,opt,name=via_service,json=viaService,proto3,oneof"`
}
type SidecarVersionSpec_ViaStatefulSet struct {
	ViaStatefulSet *ViaStatefulSet `protobuf:"bytes,3,opt,name=via_stateful_set,json=viaStatefulSet,proto3,oneof"`
}
type SidecarVersionSpec_ViaLabelSelector struct {
	ViaLabelSelector *ViaLabelSelector `protobuf:"bytes,4,opt,name=via_label_selector,json=viaLabelSelector,proto3,oneof"`
}

func (*SidecarVersionSpec_ViaDeployment) isSidecarVersionSpec_Selector()    {}
func (*SidecarVersionSpec_ViaService) isSidecarVersionSpec_Selector()       {}
func (*SidecarVersionSpec_ViaStatefulSet) isSidecarVersionSpec_Selector()   {}
func (*SidecarVersionSpec_ViaLabelSelector) isSidecarVersionSpec_Selector() {}

func (m *SidecarVersionSpec) GetSelector() isSidecarVersionSpec_Selector {
	if m != nil {
		return m.Selector
	}
	return nil
}

func (m *SidecarVersionSpec) GetViaDeployment() *ViaDeployment {
	if x, ok := m.GetSelector().(*SidecarVersionSpec_ViaDeployment); ok {
		return x.ViaDeployment
	}
	return nil
}

func (m *SidecarVersionSpec) GetViaService() *ViaService {
	if x, ok := m.GetSelector().(*SidecarVersionSpec_ViaService); ok {
		return x.ViaService
	}
	return nil
}

func (m *SidecarVersionSpec) GetViaStatefulSet() *ViaStatefulSet {
	if x, ok := m.GetSelector().(*SidecarVersionSpec_ViaStatefulSet); ok {
		return x.ViaStatefulSet
	}
	return nil
}

func (m *SidecarVersionSpec) GetViaLabelSelector() *ViaLabelSelector {
	if x, ok := m.GetSelector().(*SidecarVersionSpec_ViaLabelSelector); ok {
		return x.ViaLabelSelector
	}
	return nil
}

func (m *SidecarVersionSpec) GetExpectedVersion() string {
	if m != nil {
		return m.ExpectedVersion
	}
	return ""
}

func (m *SidecarVersionSpec) GetPodsHash() string {
	if m != nil {
		return m.PodsHash
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SidecarVersionSpec) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SidecarVersionSpec_OneofMarshaler, _SidecarVersionSpec_OneofUnmarshaler, _SidecarVersionSpec_OneofSizer, []interface{}{
		(*SidecarVersionSpec_ViaDeployment)(nil),
		(*SidecarVersionSpec_ViaService)(nil),
		(*SidecarVersionSpec_ViaStatefulSet)(nil),
		(*SidecarVersionSpec_ViaLabelSelector)(nil),
	}
}

func _SidecarVersionSpec_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SidecarVersionSpec)
	// selector
	switch x := m.Selector.(type) {
	case *SidecarVersionSpec_ViaDeployment:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ViaDeployment); err != nil {
			return err
		}
	case *SidecarVersionSpec_ViaService:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ViaService); err != nil {
			return err
		}
	case *SidecarVersionSpec_ViaStatefulSet:
		_ = b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ViaStatefulSet); err != nil {
			return err
		}
	case *SidecarVersionSpec_ViaLabelSelector:
		_ = b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ViaLabelSelector); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SidecarVersionSpec.Selector has unexpected type %T", x)
	}
	return nil
}

func _SidecarVersionSpec_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SidecarVersionSpec)
	switch tag {
	case 1: // selector.via_deployment
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ViaDeployment)
		err := b.DecodeMessage(msg)
		m.Selector = &SidecarVersionSpec_ViaDeployment{msg}
		return true, err
	case 2: // selector.via_service
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ViaService)
		err := b.DecodeMessage(msg)
		m.Selector = &SidecarVersionSpec_ViaService{msg}
		return true, err
	case 3: // selector.via_stateful_set
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ViaStatefulSet)
		err := b.DecodeMessage(msg)
		m.Selector = &SidecarVersionSpec_ViaStatefulSet{msg}
		return true, err
	case 4: // selector.via_label_selector
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ViaLabelSelector)
		err := b.DecodeMessage(msg)
		m.Selector = &SidecarVersionSpec_ViaLabelSelector{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SidecarVersionSpec_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SidecarVersionSpec)
	// selector
	switch x := m.Selector.(type) {
	case *SidecarVersionSpec_ViaDeployment:
		s := proto.Size(x.ViaDeployment)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SidecarVersionSpec_ViaService:
		s := proto.Size(x.ViaService)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SidecarVersionSpec_ViaStatefulSet:
		s := proto.Size(x.ViaStatefulSet)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SidecarVersionSpec_ViaLabelSelector:
		s := proto.Size(x.ViaLabelSelector)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ViaDeployment struct {
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViaDeployment) Reset()         { *m = ViaDeployment{} }
func (m *ViaDeployment) String() string { return proto.CompactTextString(m) }
func (*ViaDeployment) ProtoMessage()    {}
func (*ViaDeployment) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec525f68b6c4927b, []int{2}
}
func (m *ViaDeployment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ViaDeployment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ViaDeployment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ViaDeployment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViaDeployment.Merge(m, src)
}
func (m *ViaDeployment) XXX_Size() int {
	return m.Size()
}
func (m *ViaDeployment) XXX_DiscardUnknown() {
	xxx_messageInfo_ViaDeployment.DiscardUnknown(m)
}

var xxx_messageInfo_ViaDeployment proto.InternalMessageInfo

func (m *ViaDeployment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ViaService struct {
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViaService) Reset()         { *m = ViaService{} }
func (m *ViaService) String() string { return proto.CompactTextString(m) }
func (*ViaService) ProtoMessage()    {}
func (*ViaService) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec525f68b6c4927b, []int{3}
}
func (m *ViaService) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ViaService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ViaService.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ViaService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViaService.Merge(m, src)
}
func (m *ViaService) XXX_Size() int {
	return m.Size()
}
func (m *ViaService) XXX_DiscardUnknown() {
	xxx_messageInfo_ViaService.DiscardUnknown(m)
}

var xxx_messageInfo_ViaService proto.InternalMessageInfo

func (m *ViaService) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ViaStatefulSet struct {
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViaStatefulSet) Reset()         { *m = ViaStatefulSet{} }
func (m *ViaStatefulSet) String() string { return proto.CompactTextString(m) }
func (*ViaStatefulSet) ProtoMessage()    {}
func (*ViaStatefulSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec525f68b6c4927b, []int{4}
}
func (m *ViaStatefulSet) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ViaStatefulSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ViaStatefulSet.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ViaStatefulSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViaStatefulSet.Merge(m, src)
}
func (m *ViaStatefulSet) XXX_Size() int {
	return m.Size()
}
func (m *ViaStatefulSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ViaStatefulSet.DiscardUnknown(m)
}

var xxx_messageInfo_ViaStatefulSet proto.InternalMessageInfo

func (m *ViaStatefulSet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ViaLabelSelector struct {
	Labels               map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ViaLabelSelector) Reset()         { *m = ViaLabelSelector{} }
func (m *ViaLabelSelector) String() string { return proto.CompactTextString(m) }
func (*ViaLabelSelector) ProtoMessage()    {}
func (*ViaLabelSelector) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec525f68b6c4927b, []int{5}
}
func (m *ViaLabelSelector) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ViaLabelSelector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ViaLabelSelector.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ViaLabelSelector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViaLabelSelector.Merge(m, src)
}
func (m *ViaLabelSelector) XXX_Size() int {
	return m.Size()
}
func (m *ViaLabelSelector) XXX_DiscardUnknown() {
	xxx_messageInfo_ViaLabelSelector.DiscardUnknown(m)
}

var xxx_messageInfo_ViaLabelSelector proto.InternalMessageInfo

func (m *ViaLabelSelector) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type RetryPolicy struct {
	NeverRetry           bool            `protobuf:"varint,1,opt,name=never_retry,json=neverRetry,proto3" json:"never_retry,omitempty"`
	RetryTime            int64           `protobuf:"varint,2,opt,name=retry_time,json=retryTime,proto3" json:"retry_time,omitempty"`
	RetryInterval        *types.Duration `protobuf:"bytes,3,opt,name=retry_interval,json=retryInterval,proto3" json:"retry_interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RetryPolicy) Reset()         { *m = RetryPolicy{} }
func (m *RetryPolicy) String() string { return proto.CompactTextString(m) }
func (*RetryPolicy) ProtoMessage()    {}
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec525f68b6c4927b, []int{6}
}
func (m *RetryPolicy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RetryPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RetryPolicy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RetryPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetryPolicy.Merge(m, src)
}
func (m *RetryPolicy) XXX_Size() int {
	return m.Size()
}
func (m *RetryPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_RetryPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_RetryPolicy proto.InternalMessageInfo

func (m *RetryPolicy) GetNeverRetry() bool {
	if m != nil {
		return m.NeverRetry
	}
	return false
}

func (m *RetryPolicy) GetRetryTime() int64 {
	if m != nil {
		return m.RetryTime
	}
	return 0
}

func (m *RetryPolicy) GetRetryInterval() *types.Duration {
	if m != nil {
		return m.RetryInterval
	}
	return nil
}

type Status struct {
	SyncTime             string              `protobuf:"bytes,1,opt,name=sync_time,json=syncTime,proto3" json:"sync_time,omitempty"`
	PodVersionStatus     []*PodVersionStatus `protobuf:"bytes,2,rep,name=pod_version_status,json=podVersionStatus,proto3" json:"pod_version_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec525f68b6c4927b, []int{7}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Status.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return m.Size()
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetSyncTime() string {
	if m != nil {
		return m.SyncTime
	}
	return ""
}

func (m *Status) GetPodVersionStatus() []*PodVersionStatus {
	if m != nil {
		return m.PodVersionStatus
	}
	return nil
}

type PodVersionStatus struct {
	PodName        string `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	CurrentVersion string `protobuf:"bytes,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	LastUpdateTime string `protobuf:"bytes,3,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"last_update_time,omitempty"`
	//todo: implement
	StatusCode int32 `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	//todo：implement
	StatusMessage        string   `protobuf:"bytes,5,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodVersionStatus) Reset()         { *m = PodVersionStatus{} }
func (m *PodVersionStatus) String() string { return proto.CompactTextString(m) }
func (*PodVersionStatus) ProtoMessage()    {}
func (*PodVersionStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec525f68b6c4927b, []int{8}
}
func (m *PodVersionStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PodVersionStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PodVersionStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PodVersionStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodVersionStatus.Merge(m, src)
}
func (m *PodVersionStatus) XXX_Size() int {
	return m.Size()
}
func (m *PodVersionStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_PodVersionStatus.DiscardUnknown(m)
}

var xxx_messageInfo_PodVersionStatus proto.InternalMessageInfo

func (m *PodVersionStatus) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *PodVersionStatus) GetCurrentVersion() string {
	if m != nil {
		return m.CurrentVersion
	}
	return ""
}

func (m *PodVersionStatus) GetLastUpdateTime() string {
	if m != nil {
		return m.LastUpdateTime
	}
	return ""
}

func (m *PodVersionStatus) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *PodVersionStatus) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionManager)(nil), "istio.networking.v1alpha3.VersionManager")
	proto.RegisterType((*SidecarVersionSpec)(nil), "istio.networking.v1alpha3.SidecarVersionSpec")
	proto.RegisterType((*ViaDeployment)(nil), "istio.networking.v1alpha3.ViaDeployment")
	proto.RegisterType((*ViaService)(nil), "istio.networking.v1alpha3.ViaService")
	proto.RegisterType((*ViaStatefulSet)(nil), "istio.networking.v1alpha3.ViaStatefulSet")
	proto.RegisterType((*ViaLabelSelector)(nil), "istio.networking.v1alpha3.ViaLabelSelector")
	proto.RegisterMapType((map[string]string)(nil), "istio.networking.v1alpha3.ViaLabelSelector.LabelsEntry")
	proto.RegisterType((*RetryPolicy)(nil), "istio.networking.v1alpha3.RetryPolicy")
	proto.RegisterType((*Status)(nil), "istio.networking.v1alpha3.Status")
	proto.RegisterType((*PodVersionStatus)(nil), "istio.networking.v1alpha3.PodVersionStatus")
}

func init() {
	proto.RegisterFile("networking/v1alpha3/version_manager.proto", fileDescriptor_ec525f68b6c4927b)
}

var fileDescriptor_ec525f68b6c4927b = []byte{
	// 756 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x36, 0x25, 0x5b, 0x95, 0x86, 0x95, 0x2c, 0x2c, 0x7c, 0x90, 0x5d, 0x54, 0x56, 0xd5, 0xba,
	0x95, 0x51, 0x94, 0x42, 0xed, 0x43, 0xeb, 0x9c, 0x02, 0xc7, 0x01, 0x64, 0x20, 0x4e, 0x1c, 0x2a,
	0x36, 0x90, 0xe4, 0x40, 0xac, 0xc9, 0xb1, 0x44, 0x98, 0xe2, 0x12, 0xbb, 0x4b, 0x26, 0xba, 0xe5,
	0x0d, 0xf2, 0x06, 0x41, 0x5e, 0x23, 0x6f, 0xe0, 0x63, 0x1e, 0x21, 0xf0, 0x93, 0x04, 0xdc, 0x5d,
	0x5a, 0xf2, 0x4f, 0x14, 0xe4, 0xc6, 0xfd, 0xf4, 0xcd, 0xb7, 0x33, 0xdf, 0xce, 0x8c, 0x60, 0x3b,
	0x46, 0xf9, 0x86, 0xf1, 0x8b, 0x30, 0x1e, 0xf5, 0xb3, 0x7f, 0x69, 0x94, 0x8c, 0xe9, 0x6e, 0x3f,
	0x43, 0x2e, 0x42, 0x16, 0x7b, 0x13, 0x1a, 0xd3, 0x11, 0x72, 0x27, 0xe1, 0x4c, 0x32, 0xb2, 0x1e,
	0x0a, 0x19, 0x32, 0x67, 0x16, 0xe0, 0x14, 0x01, 0x1b, 0xed, 0x11, 0x63, 0xa3, 0x08, 0xfb, 0x8a,
	0x78, 0x96, 0x9e, 0xf7, 0x83, 0x94, 0x53, 0x19, 0xb2, 0x58, 0x87, 0x76, 0x3f, 0x96, 0xa0, 0x71,
	0xaa, 0x45, 0x8f, 0xb4, 0x26, 0xf9, 0x0b, 0x56, 0x03, 0x3c, 0xa7, 0x69, 0x24, 0x3d, 0x73, 0x5d,
	0xcb, 0xea, 0x58, 0xbd, 0x9a, 0xdb, 0x30, 0xb0, 0xe1, 0x93, 0x43, 0xf8, 0x99, 0xa3, 0xe4, 0x53,
	0x2f, 0x61, 0x51, 0xe8, 0x4f, 0x5b, 0xcb, 0x1d, 0xab, 0x67, 0xef, 0xfc, 0xe9, 0x7c, 0x33, 0x1b,
	0xc7, 0xcd, 0xe9, 0xc7, 0x8a, 0xed, 0xda, 0x7c, 0x76, 0x20, 0x1e, 0xac, 0x89, 0x30, 0x40, 0x9f,
	0xf2, 0xe2, 0x4e, 0x4f, 0x24, 0xe8, 0xb7, 0x4a, 0x9d, 0x72, 0xcf, 0xde, 0xf9, 0x67, 0x81, 0xe4,
	0x50, 0x87, 0x99, 0x9c, 0x86, 0x09, 0xfa, 0x2e, 0x11, 0x77, 0x30, 0xb2, 0x07, 0x15, 0x21, 0xa9,
	0x4c, 0x45, 0xab, 0xa2, 0xb2, 0xfc, 0x6d, 0x91, 0xa4, 0x22, 0xba, 0x26, 0xa0, 0xfb, 0xa9, 0x0c,
	0xe4, 0xee, 0x2d, 0xe4, 0x39, 0x34, 0xb2, 0x90, 0x7a, 0x01, 0x26, 0x11, 0x9b, 0x4e, 0x30, 0x96,
	0xca, 0x25, 0x7b, 0xa7, 0xb7, 0x40, 0xf9, 0x34, 0xa4, 0x07, 0xd7, 0xfc, 0xc1, 0x92, 0x5b, 0xcf,
	0xe6, 0x01, 0x32, 0x00, 0x3b, 0x97, 0x14, 0xc8, 0xb3, 0xd0, 0xc7, 0x56, 0x49, 0xe9, 0x6d, 0x2d,
	0xd6, 0x1b, 0x6a, 0xf2, 0x60, 0xc9, 0x85, 0xec, 0xfa, 0x44, 0x4e, 0xa0, 0xa9, 0x94, 0x24, 0x95,
	0x78, 0x9e, 0x46, 0x9e, 0x40, 0xd9, 0x2a, 0x2b, 0xb9, 0xed, 0xef, 0xc8, 0x99, 0x88, 0x21, 0xe6,
	0xf9, 0xe5, 0x15, 0xce, 0x21, 0xe4, 0x35, 0x90, 0x5c, 0x36, 0xa2, 0x67, 0x98, 0x6b, 0x46, 0xe8,
	0x4b, 0xc6, 0xcd, 0xbb, 0xff, 0xbd, 0x58, 0xf8, 0x49, 0x1e, 0x33, 0x34, 0x21, 0x83, 0x25, 0x37,
	0xcf, 0xef, 0x06, 0x46, 0xb6, 0xa1, 0x89, 0x6f, 0x13, 0xf4, 0x25, 0x06, 0xd7, 0x8d, 0xb7, 0xa2,
	0x1a, 0x6f, 0xb5, 0xc0, 0x8b, 0xce, 0xfb, 0x05, 0x6a, 0x09, 0x0b, 0x84, 0x37, 0xa6, 0x62, 0xac,
	0x1e, 0xb4, 0xe6, 0x56, 0x73, 0x60, 0x40, 0xc5, 0x78, 0x1f, 0xa0, 0x5a, 0xa4, 0xd6, 0xfd, 0x1d,
	0xea, 0x37, 0x3c, 0x27, 0x04, 0x96, 0x63, 0x3a, 0xd1, 0xde, 0xd6, 0x5c, 0xf5, 0xdd, 0xed, 0x00,
	0xcc, 0x8c, 0xbc, 0x97, 0xf1, 0x07, 0x34, 0x6e, 0x7a, 0x73, 0x2f, 0xeb, 0x83, 0x05, 0xcd, 0xdb,
	0x95, 0x92, 0x67, 0x50, 0x51, 0x76, 0x09, 0xd3, 0xcb, 0xff, 0xfd, 0x80, 0x4d, 0x8e, 0x3a, 0x89,
	0xc7, 0xb1, 0xe4, 0x53, 0xd7, 0xc8, 0x6c, 0xec, 0x81, 0x3d, 0x07, 0x93, 0x26, 0x94, 0x2f, 0x70,
	0x6a, 0x26, 0x34, 0xff, 0x24, 0x6b, 0xb0, 0x92, 0xd1, 0x28, 0x2d, 0x72, 0xd3, 0x87, 0x07, 0xa5,
	0xff, 0xad, 0xee, 0x7b, 0x0b, 0xec, 0xb9, 0x11, 0x24, 0x9b, 0x60, 0xc7, 0x98, 0x21, 0xf7, 0xd4,
	0x28, 0x2a, 0x8d, 0xaa, 0x0b, 0x0a, 0x52, 0x34, 0xf2, 0x2b, 0x80, 0x9e, 0x70, 0x19, 0x9a, 0x5a,
	0xcb, 0x6e, 0x4d, 0x21, 0x2f, 0xc2, 0x09, 0x92, 0x87, 0xd0, 0xd0, 0x3f, 0x87, 0xb1, 0x44, 0x9e,
	0xd1, 0xc8, 0xf4, 0xd8, 0xba, 0xa3, 0xb7, 0x8e, 0x53, 0x6c, 0x1d, 0xe7, 0xc0, 0x6c, 0x1d, 0xb7,
	0xae, 0x02, 0x0e, 0x0d, 0xbf, 0xfb, 0xce, 0x82, 0x8a, 0x1e, 0xb7, 0xfc, 0x4d, 0xc5, 0x34, 0xf6,
	0xf5, 0x55, 0xba, 0x9c, 0x6a, 0x0e, 0xa8, 0x9b, 0x5e, 0x02, 0x49, 0x58, 0x30, 0xdb, 0x0d, 0x7a,
	0x94, 0xb5, 0xa3, 0x8b, 0x1a, 0xef, 0x98, 0x15, 0x3d, 0x63, 0x86, 0xba, 0x99, 0xdc, 0x42, 0xba,
	0x97, 0x16, 0x34, 0x6f, 0xd3, 0xc8, 0x3a, 0xe4, 0xfd, 0xe4, 0xa9, 0x27, 0xd6, 0xb9, 0xfc, 0x94,
	0xb0, 0xe0, 0x29, 0x9d, 0x60, 0xbe, 0x1e, 0xfd, 0x94, 0x73, 0x8c, 0x67, 0xeb, 0x51, 0x1b, 0xdd,
	0x30, 0x70, 0xd1, 0xa4, 0x3d, 0x68, 0x46, 0x54, 0x48, 0x2f, 0x4d, 0x02, 0x2a, 0x51, 0xd7, 0x55,
	0xd6, 0xcc, 0x1c, 0x3f, 0x51, 0xb0, 0xaa, 0x6e, 0x13, 0x6c, 0x5d, 0x91, 0xe7, 0xb3, 0x00, 0xd5,
	0x3c, 0xad, 0xb8, 0xa0, 0xa1, 0x47, 0x2c, 0x40, 0xb2, 0x05, 0x0d, 0x43, 0x98, 0xa0, 0x10, 0x74,
	0x84, 0x66, 0x30, 0xea, 0x1a, 0x3d, 0xd2, 0xe0, 0xbe, 0x73, 0x79, 0xd5, 0xb6, 0x3e, 0x5f, 0xb5,
	0xad, 0x2f, 0x57, 0x6d, 0xeb, 0x55, 0x47, 0xdb, 0x12, 0xb2, 0x3e, 0x4d, 0xc2, 0xfe, 0x3d, 0xff,
	0x26, 0x67, 0x15, 0xf5, 0x3e, 0xbb, 0x5f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x28, 0x6d, 0x21,
	0x6b, 0x06, 0x00, 0x00,
}

func (m *VersionManager) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VersionManager) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VersionManager) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Status != nil {
		{
			size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintVersionManager(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.RetryPolicy != nil {
		{
			size, err := m.RetryPolicy.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintVersionManager(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.SidecarVersionSpec) > 0 {
		for iNdEx := len(m.SidecarVersionSpec) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SidecarVersionSpec[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintVersionManager(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.DefaultVersion) > 0 {
		i -= len(m.DefaultVersion)
		copy(dAtA[i:], m.DefaultVersion)
		i = encodeVarintVersionManager(dAtA, i, uint64(len(m.DefaultVersion)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SidecarVersionSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SidecarVersionSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SidecarVersionSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.PodsHash) > 0 {
		i -= len(m.PodsHash)
		copy(dAtA[i:], m.PodsHash)
		i = encodeVarintVersionManager(dAtA, i, uint64(len(m.PodsHash)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.ExpectedVersion) > 0 {
		i -= len(m.ExpectedVersion)
		copy(dAtA[i:], m.ExpectedVersion)
		i = encodeVarintVersionManager(dAtA, i, uint64(len(m.ExpectedVersion)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Selector != nil {
		{
			size := m.Selector.Size()
			i -= size
			if _, err := m.Selector.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *SidecarVersionSpec_ViaDeployment) MarshalTo(dAtA []byte) (int, error) {
	return m.MarshalToSizedBuffer(dAtA[:m.Size()])
}

func (m *SidecarVersionSpec_ViaDeployment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.ViaDeployment != nil {
		{
			size, err := m.ViaDeployment.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintVersionManager(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *SidecarVersionSpec_ViaService) MarshalTo(dAtA []byte) (int, error) {
	return m.MarshalToSizedBuffer(dAtA[:m.Size()])
}

func (m *SidecarVersionSpec_ViaService) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.ViaService != nil {
		{
			size, err := m.ViaService.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintVersionManager(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *SidecarVersionSpec_ViaStatefulSet) MarshalTo(dAtA []byte) (int, error) {
	return m.MarshalToSizedBuffer(dAtA[:m.Size()])
}

func (m *SidecarVersionSpec_ViaStatefulSet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.ViaStatefulSet != nil {
		{
			size, err := m.ViaStatefulSet.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintVersionManager(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *SidecarVersionSpec_ViaLabelSelector) MarshalTo(dAtA []byte) (int, error) {
	return m.MarshalToSizedBuffer(dAtA[:m.Size()])
}

func (m *SidecarVersionSpec_ViaLabelSelector) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.ViaLabelSelector != nil {
		{
			size, err := m.ViaLabelSelector.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintVersionManager(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}
func (m *ViaDeployment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ViaDeployment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ViaDeployment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintVersionManager(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func (m *ViaService) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ViaService) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ViaService) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintVersionManager(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func (m *ViaStatefulSet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ViaStatefulSet) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ViaStatefulSet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintVersionManager(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func (m *ViaLabelSelector) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ViaLabelSelector) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ViaLabelSelector) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Labels) > 0 {
		for k := range m.Labels {
			v := m.Labels[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintVersionManager(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintVersionManager(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintVersionManager(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x12
		}
	}
	return len(dAtA) - i, nil
}

func (m *RetryPolicy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RetryPolicy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RetryPolicy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.RetryInterval != nil {
		{
			size, err := m.RetryInterval.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintVersionManager(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.RetryTime != 0 {
		i = encodeVarintVersionManager(dAtA, i, uint64(m.RetryTime))
		i--
		dAtA[i] = 0x10
	}
	if m.NeverRetry {
		i--
		if m.NeverRetry {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Status) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Status) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Status) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.PodVersionStatus) > 0 {
		for iNdEx := len(m.PodVersionStatus) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PodVersionStatus[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintVersionManager(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.SyncTime) > 0 {
		i -= len(m.SyncTime)
		copy(dAtA[i:], m.SyncTime)
		i = encodeVarintVersionManager(dAtA, i, uint64(len(m.SyncTime)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PodVersionStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PodVersionStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PodVersionStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.StatusMessage) > 0 {
		i -= len(m.StatusMessage)
		copy(dAtA[i:], m.StatusMessage)
		i = encodeVarintVersionManager(dAtA, i, uint64(len(m.StatusMessage)))
		i--
		dAtA[i] = 0x2a
	}
	if m.StatusCode != 0 {
		i = encodeVarintVersionManager(dAtA, i, uint64(m.StatusCode))
		i--
		dAtA[i] = 0x20
	}
	if len(m.LastUpdateTime) > 0 {
		i -= len(m.LastUpdateTime)
		copy(dAtA[i:], m.LastUpdateTime)
		i = encodeVarintVersionManager(dAtA, i, uint64(len(m.LastUpdateTime)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CurrentVersion) > 0 {
		i -= len(m.CurrentVersion)
		copy(dAtA[i:], m.CurrentVersion)
		i = encodeVarintVersionManager(dAtA, i, uint64(len(m.CurrentVersion)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.PodName) > 0 {
		i -= len(m.PodName)
		copy(dAtA[i:], m.PodName)
		i = encodeVarintVersionManager(dAtA, i, uint64(len(m.PodName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintVersionManager(dAtA []byte, offset int, v uint64) int {
	offset -= sovVersionManager(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *VersionManager) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DefaultVersion)
	if l > 0 {
		n += 1 + l + sovVersionManager(uint64(l))
	}
	if len(m.SidecarVersionSpec) > 0 {
		for _, e := range m.SidecarVersionSpec {
			l = e.Size()
			n += 1 + l + sovVersionManager(uint64(l))
		}
	}
	if m.RetryPolicy != nil {
		l = m.RetryPolicy.Size()
		n += 1 + l + sovVersionManager(uint64(l))
	}
	if m.Status != nil {
		l = m.Status.Size()
		n += 1 + l + sovVersionManager(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SidecarVersionSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Selector != nil {
		n += m.Selector.Size()
	}
	l = len(m.ExpectedVersion)
	if l > 0 {
		n += 1 + l + sovVersionManager(uint64(l))
	}
	l = len(m.PodsHash)
	if l > 0 {
		n += 1 + l + sovVersionManager(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SidecarVersionSpec_ViaDeployment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ViaDeployment != nil {
		l = m.ViaDeployment.Size()
		n += 1 + l + sovVersionManager(uint64(l))
	}
	return n
}
func (m *SidecarVersionSpec_ViaService) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ViaService != nil {
		l = m.ViaService.Size()
		n += 1 + l + sovVersionManager(uint64(l))
	}
	return n
}
func (m *SidecarVersionSpec_ViaStatefulSet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ViaStatefulSet != nil {
		l = m.ViaStatefulSet.Size()
		n += 1 + l + sovVersionManager(uint64(l))
	}
	return n
}
func (m *SidecarVersionSpec_ViaLabelSelector) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ViaLabelSelector != nil {
		l = m.ViaLabelSelector.Size()
		n += 1 + l + sovVersionManager(uint64(l))
	}
	return n
}
func (m *ViaDeployment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovVersionManager(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ViaService) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovVersionManager(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ViaStatefulSet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovVersionManager(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ViaLabelSelector) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Labels) > 0 {
		for k, v := range m.Labels {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovVersionManager(uint64(len(k))) + 1 + len(v) + sovVersionManager(uint64(len(v)))
			n += mapEntrySize + 1 + sovVersionManager(uint64(mapEntrySize))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *RetryPolicy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NeverRetry {
		n += 2
	}
	if m.RetryTime != 0 {
		n += 1 + sovVersionManager(uint64(m.RetryTime))
	}
	if m.RetryInterval != nil {
		l = m.RetryInterval.Size()
		n += 1 + l + sovVersionManager(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Status) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SyncTime)
	if l > 0 {
		n += 1 + l + sovVersionManager(uint64(l))
	}
	if len(m.PodVersionStatus) > 0 {
		for _, e := range m.PodVersionStatus {
			l = e.Size()
			n += 1 + l + sovVersionManager(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *PodVersionStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PodName)
	if l > 0 {
		n += 1 + l + sovVersionManager(uint64(l))
	}
	l = len(m.CurrentVersion)
	if l > 0 {
		n += 1 + l + sovVersionManager(uint64(l))
	}
	l = len(m.LastUpdateTime)
	if l > 0 {
		n += 1 + l + sovVersionManager(uint64(l))
	}
	if m.StatusCode != 0 {
		n += 1 + sovVersionManager(uint64(m.StatusCode))
	}
	l = len(m.StatusMessage)
	if l > 0 {
		n += 1 + l + sovVersionManager(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovVersionManager(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVersionManager(x uint64) (n int) {
	return sovVersionManager(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *VersionManager) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVersionManager
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VersionManager: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VersionManager: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVersionManager
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVersionManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DefaultVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SidecarVersionSpec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVersionManager
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVersionManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SidecarVersionSpec = append(m.SidecarVersionSpec, &SidecarVersionSpec{})
			if err := m.SidecarVersionSpec[len(m.SidecarVersionSpec)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetryPolicy", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVersionManager
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVersionManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RetryPolicy == nil {
				m.RetryPolicy = &RetryPolicy{}
			}
			if err := m.RetryPolicy.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVersionManager
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVersionManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Status == nil {
				m.Status = &Status{}
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVersionManager(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthVersionManager
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthVersionManager
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SidecarVersionSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVersionManager
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SidecarVersionSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SidecarVersionSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ViaDeployment", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVersionManager
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVersionManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ViaDeployment{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Selector = &SidecarVersionSpec_ViaDeployment{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ViaService", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVersionManager
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVersionManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ViaService{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Selector = &SidecarVersionSpec_ViaService{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ViaStatefulSet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVersionManager
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVersionManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ViaStatefulSet{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Selector = &SidecarVersionSpec_ViaStatefulSet{v}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ViaLabelSelector", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVersionManager
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVersionManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ViaLabelSelector{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Selector = &SidecarVersionSpec_ViaLabelSelector{v}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpectedVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVersionManager
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVersionManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExpectedVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PodsHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVersionManager
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVersionManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PodsHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVersionManager(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthVersionManager
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthVersionManager
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ViaDeployment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVersionManager
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ViaDeployment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ViaDeployment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVersionManager
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVersionManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVersionManager(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthVersionManager
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthVersionManager
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ViaService) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVersionManager
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ViaService: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ViaService: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVersionManager
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVersionManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVersionManager(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthVersionManager
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthVersionManager
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ViaStatefulSet) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVersionManager
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ViaStatefulSet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ViaStatefulSet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVersionManager
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVersionManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVersionManager(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthVersionManager
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthVersionManager
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ViaLabelSelector) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVersionManager
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ViaLabelSelector: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ViaLabelSelector: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Labels", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVersionManager
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVersionManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Labels == nil {
				m.Labels = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowVersionManager
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowVersionManager
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthVersionManager
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthVersionManager
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowVersionManager
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthVersionManager
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthVersionManager
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipVersionManager(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthVersionManager
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Labels[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVersionManager(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthVersionManager
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthVersionManager
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RetryPolicy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVersionManager
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RetryPolicy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RetryPolicy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NeverRetry", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.NeverRetry = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetryTime", wireType)
			}
			m.RetryTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RetryTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetryInterval", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVersionManager
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVersionManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RetryInterval == nil {
				m.RetryInterval = &types.Duration{}
			}
			if err := m.RetryInterval.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVersionManager(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthVersionManager
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthVersionManager
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Status) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVersionManager
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Status: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Status: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SyncTime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVersionManager
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVersionManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SyncTime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PodVersionStatus", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVersionManager
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVersionManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PodVersionStatus = append(m.PodVersionStatus, &PodVersionStatus{})
			if err := m.PodVersionStatus[len(m.PodVersionStatus)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVersionManager(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthVersionManager
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthVersionManager
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PodVersionStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVersionManager
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PodVersionStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PodVersionStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PodName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVersionManager
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVersionManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PodName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVersionManager
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVersionManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurrentVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUpdateTime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVersionManager
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVersionManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastUpdateTime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusCode", wireType)
			}
			m.StatusCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StatusCode |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusMessage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVersionManager
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVersionManager
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StatusMessage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVersionManager(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthVersionManager
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthVersionManager
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVersionManager(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVersionManager
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVersionManager
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVersionManager
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthVersionManager
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowVersionManager
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipVersionManager(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthVersionManager
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthVersionManager = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVersionManager   = fmt.Errorf("proto: integer overflow")
)
